- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: 'yes'
    cache_valid_time: 86400 
- name: Install vim and pip
  apt:
    name:
    - vim
    - python3-pip
    - unzip
    state: present
