# DHCP: VM's on vmbr1 will automatically receive addresses
- name: Install DHCP Server
  apt:
    name: isc-dhcp-server
    state: present

- name: DHCP config - gives out addresses 10.10.10.10 to 10.10.10.99 on vmbr1
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify:
   - restart isc-dhcp-server

- name: DHCP config
  copy:
    src: isc-dhcp-server
    dest: /etc/default/isc-dhcp-server
  notify:
   - restart isc-dhcp-server
