# NOTE: this step needs to find a way to be idempotent using the proxmox cli.
# If a template already exists it should not create it.

- name: Create a temporary location to store the packer template
  file:
    state: directory
    path: /tmp/packer-template

# Dont use unarchive's remote src because it doesnt support redirects.
# github uses many redirects .
- name: Download packer template from github
  get_url: 
    url: https://github.com/chriswayg/packer-proxmox-templates/archive/{{packer_template_version}}.zip
    dest: /tmp/packer-template/temp_{{packer_template_version}}.zip

- name: Unarchive alpine packer template
  unarchive:
    src: /tmp/packer-template/temp_{{packer_template_version}}.zip
    dest: /tmp/packer-template
    remote_src: yes

- name: Update packer template's answers to change the distro repos
  copy:
    src: answers
    dest: /tmp/packer-template/packer-proxmox-templates-{{packer_template_version}}/{{alpine_template_dir}}/http/answers
    owner: root
    group: root
    mode: 0644

- name: Update packer template's build.conf
  copy:
    src: build.conf
    dest: /tmp/packer-template/packer-proxmox-templates-{{packer_template_version}}/{{alpine_template_dir}}/build.conf
    owner: root
    group: root
    mode: 0644

- name: Update packer template's server-template-vars
  copy:
    src: server-template-vars.yml
    dest: /tmp/packer-template/packer-proxmox-templates-{{packer_template_version}}/{{alpine_template_dir}}/playbook/server-template-vars.yml
    owner: root
    group: root
    mode: 0644

- name: Replace vmbr1 with vmbr0.
  replace:
    path: /tmp/packer-template/packer-proxmox-templates-{{packer_template_version}}/{{alpine_template_dir}}/alpine-3-amd64-proxmox.json
    regexp: 'vmbr1'
    replace: 'vmbr0'

- name: Execute ansible packer script.
  shell: ../build.sh proxmox
  environment:
    proxmox_password: "{{ proxmox_password }}"
    ssh_password: "{{ vm_ssh_password }}"
  args:
    executable: /bin/bash
    chdir: /tmp/packer-template/packer-proxmox-templates-{{packer_template_version}}/{{alpine_template_dir}}